### ISSUE TITLE
Compressed Iron Gear has no recipe

### ISSUE THREAD

**Issue by Xiaminou** [desht/pnc-repressurized#49]
As far as JEI can tell.
This used to be the recipe: https://ftbwiki.org/Compressed_Iron_Gear
But now I would make change the stone gear for an iron ingot, the way Thermal Foundation does it.

**Comment by Zixxl** [comment]
It seems that the recipe is currently deactivated in the source code. Shouldn't be that much work to get the integration for BuildCraft activated. 

Since the compressed iron gear is necessary for the Flux Compressor (which can be used without BuildCraft) there should also be an BuildCraft independent recipe.

**Comment by desht** [comment]
I'm just going to activate this unconditionally.  Pretty sure it was only conditional in the past because the Flux Compressor wasn't always available (needed CoFH RP API).  Now the Flux Compressor uses native Forge Energy, it's always available.
